function toList(items, fallback = 'No material findings were identified during automated screening.') {
  if (!items || items.length === 0) return `<p>${fallback}</p>`;
  return `<ul>${items.map((item) => `<li>${item}</li>`).join('')}</ul>`;
}

function formatReport(intel) {
  const { input, risk, corporate, sanctions, media, cyber, offshore, generatedAt } = intel;

  const sanctionsSummary = sanctions.matches.slice(0, 5).map((m) => {
    const caption = m?.caption || m?.properties?.name?.[0] || 'Potential match';
    return `${caption}`;
  });

  const corpSummary = corporate.opencorporates.slice(0, 5).map((entry) => {
    const company = entry.company;
    return `${company?.name || 'Unknown entity'} (${company?.jurisdiction_code || 'N/A'}) - ${company?.company_type || 'Company record'}`;
  });

  const mediaSummary = [
    ...media.gdelt.slice(0, 4).map((a) => `${a.title} (${a.seendate || 'Unknown date'})`),
    ...media.googleNews.slice(0, 4).map((a) => `${a.title}`),
  ];

  const riskColor = risk.classification === 'High Risk' ? '#dc2626' : risk.classification === 'Medium Risk' ? '#d97706' : '#16a34a';

  return {
    title: `${input.companyName} - AI Forensic Due Diligence Report`,
    html: `
      <article class="report-document">
        <section class="report-cover">
          <div>
            <h1>AI Forensic Due Diligence Engine</h1>
            <h2>${input.companyName}</h2>
            <p><strong>Country:</strong> ${input.country}</p>
            <p><strong>Date:</strong> ${new Date(generatedAt).toLocaleString()}</p>
            <p><strong>Generated by:</strong> AI Intelligence Workflow</p>
          </div>
          <div class="risk-chip" style="background:${riskColor}">${risk.classification} (${risk.score}/100)</div>
        </section>

        <section>
          <h3>Executive Summary</h3>
          <p>${input.companyName} was screened across sanctions datasets, corporate registries, open-source media, and cyber footprint indicators. Automated risk scoring indicates <strong>${risk.classification}</strong> exposure with a cumulative score of <strong>${risk.score}/100</strong>.</p>
        </section>

        <section>
          <h3>Corporate Overview</h3>
          ${toList(corpSummary)}
        </section>

        <section>
          <h3>Ownership & Management</h3>
          <p>Public beneficial ownership records are jurisdiction-dependent. Analysts should validate directors, UBOs, and controlling interests through local registries where available.</p>
        </section>

        <section>
          <h3>Sanctions & Watchlist Screening</h3>
          ${toList(sanctionsSummary)}
        </section>

        <section>
          <h3>Adverse Media Analysis</h3>
          ${toList(mediaSummary)}
          ${media.perplexitySummary ? `<div class="note-box"><strong>AI Intelligence Brief:</strong><p>${media.perplexitySummary}</p></div>` : ''}
        </section>

        <section>
          <h3>Legal & Litigation Indicators</h3>
          <p>No direct litigation API integration was conclusive in this run. Treat this section as requiring manual legal database follow-up for high-value partnerships.</p>
        </section>

        <section>
          <h3>Financial / Operational Red Flags</h3>
          ${toList(risk.signals.map((signal) => `${signal.category}: ${signal.detail}`), 'No red flags reached scoring threshold in this run.')}
        </section>

        <section>
          <h3>Domain & Cyber Intelligence</h3>
          <p><strong>Domain:</strong> ${cyber.domain || 'N/A'}</p>
          <p><strong>DNS records identified:</strong> ${cyber.dnsAnswers?.length || 0}</p>
          <p><strong>SSL transparency:</strong> ${cyber.sslSignals || 'N/A'}</p>
        </section>

        <section>
          <h3>Reputation & Public Presence</h3>
          <p>${corporate.wikipedia?.extract || 'No encyclopedic profile found. Public footprint may be limited or localized in non-English sources.'}</p>
        </section>

        <section>
          <h3>Risk Score Assessment</h3>
          <div class="heatmap">
            <div style="width:${risk.score}%; background:${riskColor}"></div>
          </div>
          <p>Final Classification: <strong>${risk.classification}</strong></p>
        </section>

        <section>
          <h3>Source References</h3>
          ${toList(intel.sourceReferences.map((s) => `<a href="${s}" target="_blank" rel="noopener noreferrer">${s}</a>`))}
          <p class="timestamp">Intelligence timestamp: ${generatedAt}</p>
        </section>
      </article>
    `,
  };
}

module.exports = { formatReport };
